project:
  type: book
  output-dir: docs
  post-render: scripts/post_script.R

book:
  title: "Open Data sources"
  subtitle: "(and how to deal with it)"
  author: "Grzegorz Sapijaszko"
  date: "2024-01-07"
  site-url: http:://www.sapijaszko.net/open/
  repo-url: https://github.com/gsapijaszko/open_data
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
#    - intro.qmd
    - osm.qmd
    - environments.qmd
#    - summary.qmd
    - references.qmd

bibliography: 
    - references.bib
    - packages.bib

format:
  html:
    theme: cosmo
    css: styles.css
    number-depth: 3
    toc-depth: 4
    link-external-newwindow: true
    grid: 
      margin-width: 350px
      body-width: 850px

  # pdf:
  #   number-depth: 3
  #   documentclass: scrreprt
  #   include-in-header: 
  #     text: |
  #       \usepackage{makeidx}
  #       \makeindex
  #   include-after-body: 
  #     text: |
  #       \printindex

editor: source

jupyter: python3

execute:
  freeze: auto
  cache: true


