install.packages(c("curl", "pak", "quarto"))
pak::pak(c("RefManageR", "quanteda", "wordcloud", "osmextract", "osmdata"))
pak::pak(c("geodata", "kableExtra", "WikidataR", "imager", "magick", "maptiles"))
pak::pak(c("mtennekes/cols4all", "r-tmap/tmap"))
pak::pak(c("r-lib/keyring", "GIScience/openrouteservice-r", "softbib"))
pak::pak(c("ropensci/tabulizerjars", "ropensci/tabulapdf@bfc79cb128f284eceeecc310b9b957bbfb9dd719"))
pak::pak(c("davidcarslaw/worldmet", "davidcarslaw/openair", "prcwiek/pmetar", "bluegreen-labs/ecmwfr"))
pak::pak(c("cartography", "matthewkling/chelsaDL", "HelgeJentsch/ClimDatDownloadR", "CopernicusDEM"))
pak::pak("devtools")
devtools::install_github("meteosimon/TanDEM-R", subdir = "pkg")
pak::pak(c("elevatr", "giscoR", "osrm", "rgbif", "kadyb/rgugik", "tidygeocoder", "tidyverse"))
