install.packages(c("remotes", "pak"), repos = "https://cran.mi2.ai/")
pak::pak(c("r-spatial/sf", "r-spatial/stars","r-spatial/spdep", "r-spatial/qgisprocess", "r-spatial/RSAGA"))
pak::pak(c("rspatial/terra"))
pak::pak(c("ropensci/osmdata"))
pak::pak(c("r-tmap/tmaptools", "r-tmap/tmap"))
pak::pak(c("kadyb/rgugik", "tidyverse"))
pak::pak(c("r-lidar/lasR", "r-lidar/rlas", "r-lidar/lidR", "r-lidar/RMCC", "r-lidar/RCSF"))
pak::pak(c("Jean-Romain/ALSroads", "Jean-Romain/lidRviewer"))
pak::pak(c("paleolimbot/rbbt", "crsh/citr"))
pak::pak(c("maptiles", "Nowosad/spDataLarge"))
